import { db } from '@/db';
import { maintenanceLogs } from '@/db/schema';

async function main() {
    const now = Date.now();
    const dayInMs = 24 * 60 * 60 * 1000;
    
    const sampleLogs = [
        // Equipment 1 - 3 logs
        {
            equipmentId: 1,
            scheduleId: 1,
            title: 'Annual Preventive Maintenance Completed',
            description: 'Performed comprehensive annual maintenance including full system inspection, lubrication of all moving parts, calibration of sensors, and performance testing. All components functioning within normal parameters.',
            type: 'preventive',
            performedBy: 'John Smith',
            performedAt: now - 15 * dayInMs,
            duration: 180,
            status: 'completed',
            partsReplaced: '["Air filter", "Drive belt", "Lubricant"]',
            cost: 450.00,
            notes: 'Equipment running smoothly after maintenance. No issues detected.',
            createdAt: now - 15 * dayInMs,
            updatedAt: now - 15 * dayInMs,
        },
        {
            equipmentId: 1,
            scheduleId: null,
            title: 'Emergency Repair - Power Supply Replaced',
            description: 'Equipment experienced sudden power failure. Diagnosed faulty power supply unit. Replaced with new unit and conducted full system check to ensure proper operation.',
            type: 'emergency',
            performedBy: 'Mike Chen',
            performedAt: now - 45 * dayInMs,
            duration: 120,
            status: 'completed',
            partsReplaced: '["Power supply unit", "Cooling fan"]',
            cost: 1250.00,
            notes: 'Emergency call-out. Equipment back online within 2 hours.',
            createdAt: now - 45 * dayInMs,
            updatedAt: now - 45 * dayInMs,
        },
        {
            equipmentId: 1,
            scheduleId: 5,
            title: 'Quarterly Safety Inspection',
            description: 'Conducted thorough safety inspection covering electrical systems, emergency stops, guards, and operator controls. All safety features verified operational.',
            type: 'inspection',
            performedBy: 'Sarah Johnson',
            performedAt: now - 90 * dayInMs,
            duration: 60,
            status: 'completed',
            partsReplaced: '[]',
            cost: 150.00,
            notes: 'All safety systems passed inspection. No deficiencies found.',
            createdAt: now - 90 * dayInMs,
            updatedAt: now - 90 * dayInMs,
        },

        // Equipment 2 - 3 logs
        {
            equipmentId: 2,
            scheduleId: 2,
            title: 'Calibration and Performance Check',
            description: 'Performed precision calibration of all measurement systems and sensors. Verified accuracy against certified standards. Adjusted control parameters for optimal performance.',
            type: 'calibration',
            performedBy: 'Emily Davis',
            performedAt: now - 20 * dayInMs,
            duration: 150,
            status: 'completed',
            partsReplaced: null,
            cost: 380.00,
            notes: 'Calibration successful. Equipment now operating at 99.8% accuracy.',
            createdAt: now - 20 * dayInMs,
            updatedAt: now - 20 * dayInMs,
        },
        {
            equipmentId: 2,
            scheduleId: null,
            title: 'Corrective Maintenance - Belt Replacement',
            description: 'Operator reported unusual noise during operation. Inspection revealed worn drive belt. Replaced belt and adjusted tension. Tested equipment under load.',
            type: 'corrective',
            performedBy: 'Robert Wilson',
            performedAt: now - 55 * dayInMs,
            duration: 90,
            status: 'completed',
            partsReplaced: '["Drive belt", "Tensioner pulley"]',
            cost: 275.50,
            notes: 'Noise eliminated. Equipment running smoothly.',
            createdAt: now - 55 * dayInMs,
            updatedAt: now - 55 * dayInMs,
        },
        {
            equipmentId: 2,
            scheduleId: 6,
            title: 'Filter and Component Replacement',
            description: 'Replaced hydraulic filter and coolant filter as part of scheduled maintenance. Checked fluid levels and topped up as needed. Inspected hoses for wear.',
            type: 'preventive',
            performedBy: 'Lisa Anderson',
            performedAt: now - 120 * dayInMs,
            duration: 75,
            status: 'completed',
            partsReplaced: '["Hydraulic filter", "Coolant filter", "Hydraulic oil"]',
            cost: 320.00,
            notes: 'All filters replaced successfully. System pressure normal.',
            createdAt: now - 120 * dayInMs,
            updatedAt: now - 120 * dayInMs,
        },

        // Equipment 3 - 3 logs
        {
            equipmentId: 3,
            scheduleId: 3,
            title: 'Software Update and System Check',
            description: 'Applied latest firmware update to control system. Verified all parameters after update. Conducted functional testing of all operational modes.',
            type: 'preventive',
            performedBy: 'John Smith',
            performedAt: now - 10 * dayInMs,
            duration: 120,
            status: 'completed',
            partsReplaced: '[]',
            cost: 200.00,
            notes: 'Firmware update successful. New features now available.',
            createdAt: now - 10 * dayInMs,
            updatedAt: now - 10 * dayInMs,
        },
        {
            equipmentId: 3,
            scheduleId: null,
            title: 'Emergency Repair - Sensor Malfunction',
            description: 'Equipment shut down due to sensor error. Replaced faulty temperature sensor and recalibrated system. Performed full diagnostic check.',
            type: 'emergency',
            performedBy: 'Mike Chen',
            performedAt: now - 65 * dayInMs,
            duration: 150,
            status: 'completed',
            partsReplaced: '["Temperature sensor", "Sensor cable"]',
            cost: 890.00,
            notes: 'Sensor replaced. System recalibrated and operational.',
            createdAt: now - 65 * dayInMs,
            updatedAt: now - 65 * dayInMs,
        },
        {
            equipmentId: 3,
            scheduleId: 7,
            title: 'Monthly Performance Inspection',
            description: 'Routine monthly inspection of all major components. Checked wear patterns, lubrication levels, and operational parameters. All systems within specifications.',
            type: 'inspection',
            performedBy: 'Sarah Johnson',
            performedAt: now - 30 * dayInMs,
            duration: 45,
            status: 'completed',
            partsReplaced: null,
            cost: 125.00,
            notes: 'Equipment in good condition. No issues identified.',
            createdAt: now - 30 * dayInMs,
            updatedAt: now - 30 * dayInMs,
        },

        // Equipment 4 - 3 logs
        {
            equipmentId: 4,
            scheduleId: 4,
            title: 'Annual Preventive Maintenance Completed',
            description: 'Comprehensive annual service including complete teardown and inspection of critical components. Replaced worn parts, cleaned and lubricated all mechanisms, and performed full function test.',
            type: 'preventive',
            performedBy: 'Emily Davis',
            performedAt: now - 25 * dayInMs,
            duration: 240,
            status: 'completed',
            partsReplaced: '["Seal kit", "Bearing set", "Gaskets", "O-rings"]',
            cost: 1850.00,
            notes: 'Major service completed. Equipment certified for another year.',
            createdAt: now - 25 * dayInMs,
            updatedAt: now - 25 * dayInMs,
        },
        {
            equipmentId: 4,
            scheduleId: null,
            title: 'Corrective Maintenance - Hydraulic Leak Repair',
            description: 'Addressed hydraulic fluid leak at main cylinder connection. Replaced damaged seals and fittings. Pressure tested system to verify repair.',
            type: 'corrective',
            performedBy: 'Robert Wilson',
            performedAt: now - 75 * dayInMs,
            duration: 180,
            status: 'completed',
            partsReplaced: '["Hydraulic seals", "Fittings", "Hydraulic hose"]',
            cost: 650.00,
            notes: 'Leak repaired. System holding pressure at 3000 PSI.',
            createdAt: now - 75 * dayInMs,
            updatedAt: now - 75 * dayInMs,
        },
        {
            equipmentId: 4,
            scheduleId: 8,
            title: 'Calibration and Performance Check',
            description: 'Performed precision calibration of control systems and pressure sensors. Verified all operational parameters against manufacturer specifications.',
            type: 'calibration',
            performedBy: 'Lisa Anderson',
            performedAt: now - 135 * dayInMs,
            duration: 120,
            status: 'completed',
            partsReplaced: '[]',
            cost: 425.00,
            notes: 'Calibration within tolerance. Performance optimal.',
            createdAt: now - 135 * dayInMs,
            updatedAt: now - 135 * dayInMs,
        },

        // Equipment 5 - 3 logs
        {
            equipmentId: 5,
            scheduleId: 9,
            title: 'Quarterly Safety Inspection',
            description: 'Comprehensive safety audit covering all protective devices, emergency systems, and operator controls. Tested interlock systems and safety circuits.',
            type: 'inspection',
            performedBy: 'John Smith',
            performedAt: now - 18 * dayInMs,
            duration: 90,
            status: 'completed',
            partsReplaced: null,
            cost: 175.00,
            notes: 'All safety systems functioning correctly. Compliance verified.',
            createdAt: now - 18 * dayInMs,
            updatedAt: now - 18 * dayInMs,
        },
        {
            equipmentId: 5,
            scheduleId: null,
            title: 'Emergency Repair - Motor Overheating',
            description: 'Equipment shut down due to motor overheating alarm. Found blocked cooling vents and failed cooling fan. Cleaned vents and replaced fan motor.',
            type: 'emergency',
            performedBy: 'Mike Chen',
            performedAt: now - 50 * dayInMs,
            duration: 135,
            status: 'completed',
            partsReplaced: '["Cooling fan motor", "Fan blade assembly"]',
            cost: 780.00,
            notes: 'Cooling system restored. Temperature now normal at 45°C.',
            createdAt: now - 50 * dayInMs,
            updatedAt: now - 50 * dayInMs,
        },
        {
            equipmentId: 5,
            scheduleId: 10,
            title: 'Filter and Component Replacement',
            description: 'Replaced air filters, oil filters, and coolant. Inspected electrical connections and tightened loose terminals. Updated maintenance records.',
            type: 'preventive',
            performedBy: 'Sarah Johnson',
            performedAt: now - 95 * dayInMs,
            duration: 60,
            status: 'completed',
            partsReplaced: '["Air filter", "Oil filter", "Coolant"]',
            cost: 285.00,
            notes: 'Routine service completed. Next service due in 90 days.',
            createdAt: now - 95 * dayInMs,
            updatedAt: now - 95 * dayInMs,
        },

        // Equipment 6 - 3 logs
        {
            equipmentId: 6,
            scheduleId: 11,
            title: 'Software Update and System Check',
            description: 'Installed latest PLC firmware update. Updated HMI software to latest version. Backed up all programs and parameters before update.',
            type: 'preventive',
            performedBy: 'Emily Davis',
            performedAt: now - 12 * dayInMs,
            duration: 150,
            status: 'incomplete',
            partsReplaced: '[]',
            cost: null,
            notes: 'Update in progress. Requires additional testing before completion.',
            createdAt: now - 12 * dayInMs,
            updatedAt: now - 12 * dayInMs,
        },
        {
            equipmentId: 6,
            scheduleId: null,
            title: 'Corrective Maintenance - Pneumatic System Repair',
            description: 'Addressed loss of air pressure in pneumatic system. Found multiple leaks at cylinder connections and air lines. Replaced damaged components.',
            type: 'corrective',
            performedBy: 'Robert Wilson',
            performedAt: now - 60 * dayInMs,
            duration: 180,
            status: 'completed',
            partsReplaced: '["Air cylinders", "Pneumatic fittings", "Air lines"]',
            cost: 920.00,
            notes: 'System pressure restored to 90 PSI. No leaks detected.',
            createdAt: now - 60 * dayInMs,
            updatedAt: now - 60 * dayInMs,
        },
        {
            equipmentId: 6,
            scheduleId: 12,
            title: 'Annual Preventive Maintenance Completed',
            description: 'Complete annual overhaul including mechanical, electrical, and pneumatic systems. Replaced wear parts, calibrated sensors, and updated documentation.',
            type: 'preventive',
            performedBy: 'Lisa Anderson',
            performedAt: now - 140 * dayInMs,
            duration: 300,
            status: 'completed',
            partsReplaced: '["Valve pack", "Sensor array", "Control switches", "Air filter"]',
            cost: 2500.00,
            notes: 'Major overhaul completed. Equipment certified operational.',
            createdAt: now - 140 * dayInMs,
            updatedAt: now - 140 * dayInMs,
        },

        // Equipment 7 - 2 logs
        {
            equipmentId: 7,
            scheduleId: 13,
            title: 'Calibration and Performance Check',
            description: 'Performed calibration of all measurement instruments and verified accuracy. Adjusted control loops for optimal performance.',
            type: 'calibration',
            performedBy: 'John Smith',
            performedAt: now - 22 * dayInMs,
            duration: 120,
            status: 'completed',
            partsReplaced: null,
            cost: 395.00,
            notes: 'All instruments calibrated to factory specifications.',
            createdAt: now - 22 * dayInMs,
            updatedAt: now - 22 * dayInMs,
        },
        {
            equipmentId: 7,
            scheduleId: null,
            title: 'Emergency Repair - Control Panel Failure',
            description: 'Control panel became unresponsive during operation. Diagnosed failed PLC module. Replaced module and restored all program parameters from backup.',
            type: 'emergency',
            performedBy: 'Mike Chen',
            performedAt: now - 80 * dayInMs,
            duration: 210,
            status: 'failed',
            partsReplaced: '["PLC module", "Memory card"]',
            cost: 1450.00,
            notes: 'Initial repair attempt failed. Equipment requires additional troubleshooting.',
            createdAt: now - 80 * dayInMs,
            updatedAt: now - 80 * dayInMs,
        },

        // Equipment 8 - 2 logs
        {
            equipmentId: 8,
            scheduleId: 14,
            title: 'Quarterly Safety Inspection',
            description: 'Conducted safety inspection covering emergency stops, light curtains, and guard interlocks. Verified proper operation of all safety devices.',
            type: 'inspection',
            performedBy: 'Sarah Johnson',
            performedAt: now - 35 * dayInMs,
            duration: 75,
            status: 'completed',
            partsReplaced: '[]',
            cost: 165.00,
            notes: 'Safety inspection passed. All systems operational.',
            createdAt: now - 35 * dayInMs,
            updatedAt: now - 35 * dayInMs,
        },
        {
            equipmentId: 8,
            scheduleId: null,
            title: 'Corrective Maintenance - Bearing Replacement',
            description: 'Operator reported vibration and noise from main drive. Inspection revealed worn bearings. Replaced bearing assembly and balanced rotating components.',
            type: 'corrective',
            performedBy: 'Robert Wilson',
            performedAt: now - 105 * dayInMs,
            duration: 240,
            status: 'completed',
            partsReplaced: '["Bearing assembly", "Seal kit", "Grease"]',
            cost: 1150.00,
            notes: 'Vibration eliminated. Equipment running smoothly.',
            createdAt: now - 105 * dayInMs,
            updatedAt: now - 105 * dayInMs,
        },

        // Equipment 9 - 2 logs
        {
            equipmentId: 9,
            scheduleId: 15,
            title: 'Filter and Component Replacement',
            description: 'Replaced all consumable filters and fluids as part of preventive maintenance schedule. Inspected all components for wear.',
            type: 'preventive',
            performedBy: 'Emily Davis',
            performedAt: now - 28 * dayInMs,
            duration: 90,
            status: 'completed',
            partsReplaced: '["Air filter", "Hydraulic filter", "Coolant filter"]',
            cost: 340.00,
            notes: 'All filters replaced. Fluid levels checked and topped up.',
            createdAt: now - 28 * dayInMs,
            updatedAt: now - 28 * dayInMs,
        },
        {
            equipmentId: 9,
            scheduleId: null,
            title: 'Emergency Repair - Electrical Short Circuit',
            description: 'Equipment tripped main circuit breaker. Located short circuit in motor control circuit. Replaced damaged wiring and control components.',
            type: 'emergency',
            performedBy: 'Lisa Anderson',
            performedAt: now - 115 * dayInMs,
            duration: 180,
            status: 'completed',
            partsReplaced: '["Control relay", "Wiring harness", "Circuit breaker"]',
            cost: 825.00,
            notes: 'Short circuit repaired. System tested under full load.',
            createdAt: now - 115 * dayInMs,
            updatedAt: now - 115 * dayInMs,
        },

        // Equipment 10 - 2 logs
        {
            equipmentId: 10,
            scheduleId: 16,
            title: 'Annual Preventive Maintenance Completed',
            description: 'Complete annual service including full inspection, cleaning, lubrication, and testing of all systems. Replaced scheduled wear parts.',
            type: 'preventive',
            performedBy: 'John Smith',
            performedAt: now - 40 * dayInMs,
            duration: 270,
            status: 'completed',
            partsReplaced: '["Drive chain", "Sprockets", "Guards", "Lubricant"]',
            cost: 1680.00,
            notes: 'Annual service completed. Equipment approved for operation.',
            createdAt: now - 40 * dayInMs,
            updatedAt: now - 40 * dayInMs,
        },
        {
            equipmentId: 10,
            scheduleId: null,
            title: 'Calibration and Performance Check',
            description: 'Performed precision calibration after annual service. Verified all operational parameters and adjusted control settings for optimal performance.',
            type: 'calibration',
            performedBy: 'Mike Chen',
            performedAt: now - 38 * dayInMs,
            duration: 105,
            status: 'incomplete',
            partsReplaced: null,
            cost: null,
            notes: 'Calibration in progress. Awaiting final verification results.',
            createdAt: now - 38 * dayInMs,
            updatedAt: now - 38 * dayInMs,
        },

        // Equipment 11 - 2 logs
        {
            equipmentId: 11,
            scheduleId: 1,
            title: 'Monthly Performance Inspection',
            description: 'Routine monthly check of all operational systems. Verified performance metrics and documented current condition of equipment.',
            type: 'inspection',
            performedBy: 'Sarah Johnson',
            performedAt: now - 8 * dayInMs,
            duration: 45,
            status: 'completed',
            partsReplaced: '[]',
            cost: 130.00,
            notes: 'Equipment performing within normal parameters.',
            createdAt: now - 8 * dayInMs,
            updatedAt: now - 8 * dayInMs,
        },
        {
            equipmentId: 11,
            scheduleId: null,
            title: 'Corrective Maintenance - Valve Replacement',
            description: 'Control valve showing signs of wear and leakage. Replaced valve assembly and tested system pressure and flow rate.',
            type: 'corrective',
            performedBy: 'Robert Wilson',
            performedAt: now - 125 * dayInMs,
            duration: 150,
            status: 'incomplete',
            partsReplaced: '["Control valve", "Valve actuator"]',
            cost: 980.00,
            notes: 'Valve replaced. Requires additional pressure testing.',
            createdAt: now - 125 * dayInMs,
            updatedAt: now - 125 * dayInMs,
        },

        // Equipment 12 - 2 logs
        {
            equipmentId: 12,
            scheduleId: 2,
            title: 'Software Update and System Check',
            description: 'Applied critical security patches and performance updates to control software. Verified system stability after updates.',
            type: 'preventive',
            performedBy: 'Emily Davis',
            performedAt: now - 5 * dayInMs,
            duration: 135,
            status: 'completed',
            partsReplaced: '[]',
            cost: 250.00,
            notes: 'Software updated successfully. System running stable.',
            createdAt: now - 5 * dayInMs,
            updatedAt: now - 5 * dayInMs,
        },
        {
            equipmentId: 12,
            scheduleId: null,
            title: 'Emergency Repair - Drive Motor Failure',
            description: 'Main drive motor failed during operation. Replaced motor and coupling assembly. Performed alignment check and load test.',
            type: 'emergency',
            performedBy: 'Lisa Anderson',
            performedAt: now - 160 * dayInMs,
            duration: 300,
            status: 'completed',
            partsReplaced: '["Drive motor", "Motor coupling", "Motor mounting hardware"]',
            cost: 3200.00,
            notes: 'Motor replaced. Equipment tested and returned to service.',
            createdAt: now - 160 * dayInMs,
            updatedAt: now - 160 * dayInMs,
        },
    ];

    await db.insert(maintenanceLogs).values(sampleLogs);
    
    console.log('✅ Maintenance logs seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});