import { db } from '@/db';
import { workOrders } from '@/db/schema';

async function main() {
    const now = Date.now();
    const dayInMs = 24 * 60 * 60 * 1000;

    const sampleWorkOrders = [
        {
            equipmentId: 1,
            title: 'Investigate Display Malfunction',
            description: 'Monitor display showing intermittent flickering and color distortion. Issue occurs randomly throughout the day. Need to investigate display connections and potentially replace display unit.',
            priority: 'high',
            status: 'in_progress',
            type: 'corrective',
            reportedBy: 'Dr. Michael Brown',
            assignedTo: 'John Smith',
            createdAt: now - (45 * dayInMs),
            scheduledDate: now + (2 * dayInMs),
            completedDate: null,
            estimatedCost: 450.00,
            actualCost: null,
            notes: 'Initial diagnosis suggests faulty display cable. Replacement cable ordered.',
            updatedAt: now - (40 * dayInMs),
        },
        {
            equipmentId: 2,
            title: 'Replace Worn Mechanical Components',
            description: 'Annual inspection revealed excessive wear on moving parts. Bearings show signs of degradation and require immediate replacement to prevent equipment failure.',
            priority: 'medium',
            status: 'completed',
            type: 'preventive',
            reportedBy: 'Tech David Kim',
            assignedTo: 'Sarah Johnson',
            createdAt: now - (55 * dayInMs),
            scheduledDate: now - (35 * dayInMs),
            completedDate: now - (30 * dayInMs),
            estimatedCost: 800.00,
            actualCost: 875.50,
            notes: 'Replaced all bearings and lubricated mechanical assembly. Equipment tested and running smoothly.',
            updatedAt: now - (30 * dayInMs),
        },
        {
            equipmentId: 3,
            title: 'Emergency Repair Required - Unit Not Powering On',
            description: 'Critical equipment failure. Unit completely unresponsive with no power indicator lights. Immediate attention required as this is affecting patient care operations.',
            priority: 'critical',
            status: 'in_progress',
            type: 'emergency',
            reportedBy: 'Nurse Susan Lee',
            assignedTo: 'Mike Chen',
            createdAt: now - (2 * dayInMs),
            scheduledDate: now + (1 * dayInMs),
            completedDate: null,
            estimatedCost: 1500.00,
            actualCost: null,
            notes: 'Power supply board diagnosed as faulty. Expedited replacement part ordered.',
            updatedAt: now - (1 * dayInMs),
        },
        {
            equipmentId: 4,
            title: 'Annual Calibration Service',
            description: 'Scheduled annual calibration as per manufacturer specifications. Includes accuracy verification, parameter adjustments, and compliance documentation.',
            priority: 'medium',
            status: 'completed',
            type: 'calibration',
            reportedBy: 'Lab Manager Tom Wilson',
            assignedTo: 'Emily Davis',
            createdAt: now - (50 * dayInMs),
            scheduledDate: now - (25 * dayInMs),
            completedDate: now - (20 * dayInMs),
            estimatedCost: 450.00,
            actualCost: 450.00,
            notes: 'Calibration completed successfully. All parameters within specified tolerances. Compliance certificate issued.',
            updatedAt: now - (20 * dayInMs),
        },
        {
            equipmentId: 5,
            title: 'Preventive Maintenance Schedule',
            description: 'Quarterly preventive maintenance including cleaning, inspection of all components, firmware updates, and performance testing.',
            priority: 'medium',
            status: 'pending',
            type: 'preventive',
            reportedBy: 'Dr. Jennifer Taylor',
            assignedTo: 'Robert Wilson',
            createdAt: now - (15 * dayInMs),
            scheduledDate: now + (10 * dayInMs),
            completedDate: null,
            estimatedCost: 200.00,
            actualCost: null,
            notes: 'Scheduled as part of regular maintenance program.',
            updatedAt: now - (15 * dayInMs),
        },
        {
            equipmentId: 6,
            title: 'Noise Investigation and Repair',
            description: 'Equipment producing unusual grinding noise during operation. Sound increases with extended use. Potential bearing or motor issue requiring investigation.',
            priority: 'high',
            status: 'completed',
            type: 'corrective',
            reportedBy: 'Tech David Kim',
            assignedTo: 'John Smith',
            createdAt: now - (40 * dayInMs),
            scheduledDate: now - (28 * dayInMs),
            completedDate: now - (25 * dayInMs),
            estimatedCost: 800.00,
            actualCost: 725.00,
            notes: 'Faulty cooling fan bearing replaced. Noise eliminated. Equipment functioning normally.',
            updatedAt: now - (25 * dayInMs),
        },
        {
            equipmentId: 7,
            title: 'Software Upgrade and Testing',
            description: 'Critical software update available from manufacturer. Update includes bug fixes, security patches, and performance improvements. Requires system downtime and thorough testing.',
            priority: 'medium',
            status: 'completed',
            type: 'preventive',
            reportedBy: 'Dr. Michael Brown',
            assignedTo: 'Sarah Johnson',
            createdAt: now - (35 * dayInMs),
            scheduledDate: now - (20 * dayInMs),
            completedDate: now - (18 * dayInMs),
            estimatedCost: 200.00,
            actualCost: 200.00,
            notes: 'Software updated to version 3.2.1. All functionality tested and verified. Training materials updated.',
            updatedAt: now - (18 * dayInMs),
        },
        {
            equipmentId: 8,
            title: 'Battery Replacement Required',
            description: 'Backup battery showing decreased capacity and failing health check diagnostics. Replacement required before complete failure to ensure uninterrupted operation.',
            priority: 'high',
            status: 'pending',
            type: 'preventive',
            reportedBy: 'Lab Manager Tom Wilson',
            assignedTo: 'Mike Chen',
            createdAt: now - (10 * dayInMs),
            scheduledDate: now + (5 * dayInMs),
            completedDate: null,
            estimatedCost: 450.00,
            actualCost: null,
            notes: 'Replacement battery ordered. Scheduled during low-usage period.',
            updatedAt: now - (10 * dayInMs),
        },
        {
            equipmentId: 9,
            title: 'Sensor Calibration Adjustment',
            description: 'Routine inspection identified sensor readings outside acceptable range. Requires recalibration and verification against reference standards.',
            priority: 'medium',
            status: 'completed',
            type: 'calibration',
            reportedBy: 'Nurse Susan Lee',
            assignedTo: 'Emily Davis',
            createdAt: now - (30 * dayInMs),
            scheduledDate: now - (15 * dayInMs),
            completedDate: now - (12 * dayInMs),
            estimatedCost: 200.00,
            actualCost: 225.00,
            notes: 'Sensors recalibrated and verified. Documentation updated in quality system.',
            updatedAt: now - (12 * dayInMs),
        },
        {
            equipmentId: 10,
            title: 'Safety Inspection and Compliance Check',
            description: 'Annual safety inspection including electrical safety testing, grounding verification, and compliance with current safety standards.',
            priority: 'low',
            status: 'pending',
            type: 'inspection',
            reportedBy: 'Dr. Jennifer Taylor',
            assignedTo: 'Robert Wilson',
            createdAt: now - (20 * dayInMs),
            scheduledDate: now + (15 * dayInMs),
            completedDate: null,
            estimatedCost: 200.00,
            actualCost: null,
            notes: 'Scheduled for annual compliance verification.',
            updatedAt: now - (20 * dayInMs),
        },
        {
            equipmentId: 11,
            title: 'Temperature Control System Malfunction',
            description: 'Temperature regulation system not maintaining setpoint. Fluctuations observed during extended operation. Critical for sample integrity.',
            priority: 'critical',
            status: 'in_progress',
            type: 'emergency',
            reportedBy: 'Tech David Kim',
            assignedTo: 'John Smith',
            createdAt: now - (5 * dayInMs),
            scheduledDate: now + (1 * dayInMs),
            completedDate: null,
            estimatedCost: 3000.00,
            actualCost: null,
            notes: 'Thermostat and cooling system under investigation. Temporary monitoring in place.',
            updatedAt: now - (3 * dayInMs),
        },
        {
            equipmentId: 12,
            title: 'Routine Filter Replacement',
            description: 'Scheduled filter replacement as part of regular maintenance program. Filters showing signs of clogging affecting system performance.',
            priority: 'low',
            status: 'cancelled',
            type: 'preventive',
            reportedBy: 'Lab Manager Tom Wilson',
            assignedTo: 'Sarah Johnson',
            createdAt: now - (25 * dayInMs),
            scheduledDate: now - (10 * dayInMs),
            completedDate: null,
            estimatedCost: 200.00,
            actualCost: null,
            notes: 'Cancelled - Equipment scheduled for replacement. Filter maintenance no longer required.',
            updatedAt: now - (8 * dayInMs),
        },
    ];

    await db.insert(workOrders).values(sampleWorkOrders);
    
    console.log('✅ Work orders seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});